"""First commit

Revision ID: da3f07a391c8
Revises: 
Create Date: 2022-05-28 17:12:26.911453

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'da3f07a391c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('npm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('npm')
    )
    op.create_index(op.f('ix_mahasiswa_nama'), 'mahasiswa', ['nama'], unique=False)
    op.create_index(op.f('ix_mahasiswa_npm'), 'mahasiswa', ['npm'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mahasiswa_npm'), table_name='mahasiswa')
    op.drop_index(op.f('ix_mahasiswa_nama'), table_name='mahasiswa')
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
